name: Running

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 2.88e+7

    steps:
    - name: Download Ngrok.
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/RavensVenix/Free-VirtualDesktop/virtual/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/RavensVenix/Free-VirtualDesktop/virtual/wallpaper.bmp -OutFile wallpaper.bmp
        Invoke-WebRequest https://raw.githubusercontent.com/RavensVenix/Free-VirtualDesktop/virtual/wallpaper.bat -OutFile wallpaper.bat
        Invoke-WebRequest https://raw.githubusercontent.com/RavensVenix/Free-VirtualDesktop/virtual/loop.bat -OutFile loop.bat
    - name: Extracting Ngrok File.
      run: Expand-Archive ngrok.zip
    - name: Connect To Account Ngrok.
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Turn on Access RDP.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "Free-VirtualDesktop" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy wallpaper.bmp D:\a\wallpaper.bmp
        copy wallpaper.bat D:\a\wallpaper.bat
        ./wallpaper.bat
        ./wallpaper.bat
        ./wallpaper.bat
    - name: Make Tunnel.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
    - name: Connect To Your RDP CPU 2 Core - 7GB Ram - 256 SSD.
      run: cmd /c start.bat
    - name: Changing Wallpaper...
      run: cmd /c wallpaper.bat
    - name: Successfully Created! You Can Close Tabs Now.
      run: cmd /c loop.bat
